package com.maria.dama2014.db;


// Generated 17-sep-2013 0:44:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set modelos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }
    public Categoria(int id, String descripcion, Set modelos) {
       this.id = id;
       this.descripcion = descripcion;
       this.modelos = modelos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getModelos() {
        return this.modelos;
    }
    
    public void setModelos(Set modelos) {
        this.modelos = modelos;
    }




}


