package com.maria.dama2014.db;


// Generated 17-sep-2013 0:44:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set coloridos = new HashSet(0);

    public Color() {
    }

	
    public Color(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Color(int id, String nombre, Set coloridos) {
       this.id = id;
       this.nombre = nombre;
       this.coloridos = coloridos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getColoridos() {
        return this.coloridos;
    }
    
    public void setColoridos(Set coloridos) {
        this.coloridos = coloridos;
    }




}


