package com.maria.dama2014.db;


// Generated 17-sep-2013 0:44:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoPrenda generated by hbm2java
 */
public class EstadoPrenda  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set prendas = new HashSet(0);

    public EstadoPrenda() {
    }

	
    public EstadoPrenda(int id) {
        this.id = id;
    }
    public EstadoPrenda(int id, String nombre, Set prendas) {
       this.id = id;
       this.nombre = nombre;
       this.prendas = prendas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPrendas() {
        return this.prendas;
    }
    
    public void setPrendas(Set prendas) {
        this.prendas = prendas;
    }




}


