package com.maria.dama2014.db;


// Generated 17-sep-2013 0:44:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private Date fecha;
     private Vendedor vendedor;
     private String comando;
     private Integer categoria;

    public Log() {
    }

	
    public Log(Date fecha) {
        this.fecha = fecha;
    }
    public Log(Date fecha, Vendedor vendedor, String comando, Integer categoria) {
       this.fecha = fecha;
       this.vendedor = vendedor;
       this.comando = comando;
       this.categoria = categoria;
    }
   
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public String getComando() {
        return this.comando;
    }
    
    public void setComando(String comando) {
        this.comando = comando;
    }
    public Integer getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Integer categoria) {
        this.categoria = categoria;
    }




}


