package com.maria.dama2014.db;


// Generated 17-sep-2013 0:44:35 by Hibernate Tools 3.2.1.GA

import java.util.*;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 * Prenda generated by hbm2java
 */
public class Prenda implements java.io.Serializable {

    private int id;
    private Tallaje tallaje;
    private Colorido colorido;
    private EstadoPrenda estadoPrenda;
    private Modelo modelo;
    private Date fechaEntrada;
    private String referencia;
    private double precioCompra;
    private double precioVentaRecomendado;
    private double precioVentaActual;
    private Set ventas = new HashSet(0);

    public Prenda() {
    }

    public Prenda(int id, Tallaje tallaje, Colorido colorido, Modelo modelo, double precioCompra, double precioVentaRecomendado, double precioVentaActual) {
        this.id = id;
        this.tallaje = tallaje;
        this.colorido = colorido;
        this.modelo = modelo;
        this.precioCompra = precioCompra;
        this.precioVentaRecomendado = precioVentaRecomendado;
        this.precioVentaActual = precioVentaActual;
    }

    public Prenda(int id, Tallaje tallaje, Colorido colorido, EstadoPrenda estadoPrenda, Modelo modelo, Date fechaEntrada, String referencia, double precioCompra, double precioVentaRecomendado, double precioVentaActual, Set ventas) {
        this.id = id;
        this.tallaje = tallaje;
        this.colorido = colorido;
        this.estadoPrenda = estadoPrenda;
        this.modelo = modelo;
        this.fechaEntrada = fechaEntrada;
        this.referencia = referencia;
        this.precioCompra = precioCompra;
        this.precioVentaRecomendado = precioVentaRecomendado;
        this.precioVentaActual = precioVentaActual;
        this.ventas = ventas;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Tallaje getTallaje() {
        return this.tallaje;
    }

    public void setTallaje(Tallaje tallaje) {
        this.tallaje = tallaje;
    }

    public Colorido getColorido() {
        return this.colorido;
    }

    public void setColorido(Colorido colorido) {
        this.colorido = colorido;
    }

    public EstadoPrenda getEstadoPrenda() {
        return this.estadoPrenda;
    }

    public void setEstadoPrenda(EstadoPrenda estadoPrenda) {
        this.estadoPrenda = estadoPrenda;
    }

    public Modelo getModelo() {
        return this.modelo;
    }

    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }

    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }

    public String getReferencia() {
        return this.referencia;
    }

    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    public double getPrecioCompra() {
        return this.precioCompra;
    }

    public void setPrecioCompra(double precioCompra) {
        this.precioCompra = precioCompra;
    }

    public double getPrecioVentaRecomendado() {
        return this.precioVentaRecomendado;
    }

    public void setPrecioVentaRecomendado(double precioVentaRecomendado) {
        this.precioVentaRecomendado = precioVentaRecomendado;
    }

    public double getPrecioVentaActual() {
        return this.precioVentaActual;
    }

    public void setPrecioVentaActual(double precioVentaActual) {
        this.precioVentaActual = precioVentaActual;
    }

    public Set getVentas() {
        return this.ventas;
    }

    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }

    public ArrayList<Prenda> getByReferencia() {
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        return getByReferencia(session);
    }
    
    public ArrayList<Prenda> getByReferencia(Session session) {
        session.beginTransaction();

        Query q = session.createQuery(
                "select p from Prenda as p inner join p.modelo as m inner join p.colorido as c inner join p.tallaje as t "
                + "where display_referencia(temporada_id, proveedor_id, codigo, c.orden, t.orden) = :ref");
        q.setParameter("ref", this.getReferencia());

        List list = q.list();

        System.out.println("Consulto referencia " + this.getReferencia());

        return list.isEmpty() ? null : (ArrayList<Prenda>) list;
    }
    
    

    @Override
    public String toString() {
        return modelo.getDescripcion() + "|" + referencia + " | Talla: " + tallaje.getTalla().getValor()
                + " | Color: " + colorido.getColor().getNombre() + " | Precio: " + precioVentaActual;
    }
}
