package com.maria.dama2014.db;


// Generated 17-sep-2013 0:44:35 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.Session;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor implements java.io.Serializable {
    
    private int id;
    private String nombre;
    private String direccion;
    private String cp;
    private String localidad;
    private String provincia;
    private String telefono;
    private String movil;
    private String representante;
    private String telefonoRepresentante;
    private String comentarios;
    private Date fechaAlta;
    private Set modelos = new HashSet(0);

    public Proveedor() {
    }

    public Proveedor(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public Proveedor(int id, String nombre, String direccion, String cp, String localidad, String provincia, String telefono, String movil, String representante, String telefonoRepresentante, String comentarios, Date fechaAlta, Set modelos) {
        this.id = id;
        this.nombre = nombre;
        this.direccion = direccion;
        this.cp = cp;
        this.localidad = localidad;
        this.provincia = provincia;
        this.telefono = telefono;
        this.movil = movil;
        this.representante = representante;
        this.telefonoRepresentante = telefonoRepresentante;
        this.comentarios = comentarios;
        this.fechaAlta = fechaAlta;
        this.modelos = modelos;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getCp() {
        return this.cp;
    }

    public void setCp(String cp) {
        this.cp = cp;
    }

    public String getLocalidad() {
        return this.localidad;
    }

    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }

    public String getProvincia() {
        return this.provincia;
    }

    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getMovil() {
        return this.movil;
    }

    public void setMovil(String movil) {
        this.movil = movil;
    }

    public String getRepresentante() {
        return this.representante;
    }

    public void setRepresentante(String representante) {
        this.representante = representante;
    }

    public String getTelefonoRepresentante() {
        return this.telefonoRepresentante;
    }

    public void setTelefonoRepresentante(String telefonoRepresentante) {
        this.telefonoRepresentante = telefonoRepresentante;
    }

    public String getComentarios() {
        return this.comentarios;
    }

    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }

    public Date getFechaAlta() {
        return this.fechaAlta;
    }

    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    public Set getModelos() {
        return this.modelos;
    }

    public void setModelos(Set modelos) {
        this.modelos = modelos;
    }

    public void newProveedor() {
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        
        session.save(this);
        session.getTransaction().commit();
        
        System.out.println("He insertado bien (creo)");
    }
}
