package com.maria.dama2014.db;


// Generated 17-sep-2013 0:44:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tallaje generated by hbm2java
 */
public class Tallaje  implements java.io.Serializable {


     private int id;
     private Talla talla;
     private Modelo modelo;
     private int orden;
     private Set prendas = new HashSet(0);

    public Tallaje() {
    }

	
    public Tallaje(int id, int orden) {
        this.id = id;
        this.orden = orden;
    }
    public Tallaje(int id, Talla talla, Modelo modelo, int orden, Set prendas) {
       this.id = id;
       this.talla = talla;
       this.modelo = modelo;
       this.orden = orden;
       this.prendas = prendas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Talla getTalla() {
        return this.talla;
    }
    
    public void setTalla(Talla talla) {
        this.talla = talla;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }
    public Set getPrendas() {
        return this.prendas;
    }
    
    public void setPrendas(Set prendas) {
        this.prendas = prendas;
    }




}


