package com.maria.dama2014.db;


// Generated 17-sep-2013 0:44:35 by Hibernate Tools 3.2.1.GA


import com.maria.dama2014.HibernateSession;
import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Session;

/**
 * Temporada generated by hbm2java
 */
public class Temporada  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set modelos = new HashSet(0);

    public Temporada() {
    }

	
    public Temporada(int id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }
    public Temporada(int id, String descripcion, Set modelos) {
       this.id = id;
       this.descripcion = descripcion;
       this.modelos = modelos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getModelos() {
        return this.modelos;
    }
    
    public void setModelos(Set modelos) {
        this.modelos = modelos;
    }

    @Override
    public String toString() {
        return "Temporada{" + "id=" + id + ", descripcion=" + descripcion + '}';
    }

    public void newTemporada() {
        Session session = HibernateSession.getSession();

        System.out.println("Hasta qui cojo la sesion");
        session.beginTransaction();
        System.out.println("Hasta aqui empizo la trnsaccion");

        Serializable nuevoId = session.save(this);
        session.getTransaction().commit();

        System.out.println("He insertado bien con identificador " + nuevoId);
    }

    
     public Temporada getById(int id) {
        Session session = HibernateSession.getSession();
        session.beginTransaction();

        Temporada temp = (Temporada) session.get(Temporada.class, id);
        session.getTransaction().commit();
        
        return temp;
    }
     
    public List<Temporada> listTemporadas() {
        Session session = HibernateSession.getSession();
        session.beginTransaction();

        List<Temporada> temps = session.createQuery("from Temporada order by id").list();

        return temps;
    }


}


