package com.maria.dama2014.db;


// Generated 17-sep-2013 0:44:35 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.Session;

/**
 * Ticket generated by hbm2java
 */
public class Ticket implements java.io.Serializable {

    private int id;
    private Date fecha;
    private String tipo;
    private Double total;
    private Boolean tarjeta;
    private Set ventas = new HashSet(0);

    public Ticket() {
        //total = 0.0;
        fecha = new Date();
    }

    public Ticket(int id) {
        this.id = id;
    }

    public Ticket(int id, Date fecha, String tipo, Double total, Boolean tarjeta, Set ventas) {
        this.id = id;
        this.fecha = fecha;
        this.tipo = tipo;
        this.total = total;
        this.tarjeta = tarjeta;
        this.ventas = ventas;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public Double getTotal() {
        return this.total;
    }

    
    public void setTotal(Double total) {
        this.total = total;
    }

    public Boolean getTarjeta() {
        return this.tarjeta;
    }

    public void setTarjeta(Boolean tarjeta) {
        this.tarjeta = tarjeta;
    }

    public Set getVentas() {
        return this.ventas;
    }

    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }

    public void guardar() {
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();

        session.save(this);
        session.getTransaction().commit();

        System.out.println("He insertado el ticket ");
    }
}
