package com.maria.dama2014.db;


// Generated 17-sep-2013 0:44:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoTalla generated by hbm2java
 */
public class TipoTalla  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set tallas = new HashSet(0);
     private Set modelos = new HashSet(0);

    public TipoTalla() {
    }

	
    public TipoTalla(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public TipoTalla(int id, String nombre, Set tallas, Set modelos) {
       this.id = id;
       this.nombre = nombre;
       this.tallas = tallas;
       this.modelos = modelos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTallas() {
        return this.tallas;
    }
    
    public void setTallas(Set tallas) {
        this.tallas = tallas;
    }
    public Set getModelos() {
        return this.modelos;
    }
    
    public void setModelos(Set modelos) {
        this.modelos = modelos;
    }




}


