package com.maria.dama2014.db;


// Generated 17-sep-2013 0:44:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String pwd;
     private Set logs = new HashSet(0);

    public Vendedor() {
    }

	
    public Vendedor(int id, String nombre, String pwd) {
        this.id = id;
        this.nombre = nombre;
        this.pwd = pwd;
    }
    public Vendedor(int id, String nombre, String pwd, Set logs) {
       this.id = id;
       this.nombre = nombre;
       this.pwd = pwd;
       this.logs = logs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }




}


