package com.maria.dama2014.db;


// Generated 17-sep-2013 0:44:35 by Hibernate Tools 3.2.1.GA

import org.hibernate.Session;




/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int id;
     private Ticket ticket;
     private Prenda prenda;
     private Double precio;

    public Venta() {
    }

	
    public Venta(int id) {
        this.id = id;
    }
    public Venta(int id, Ticket ticket, Prenda prenda, Double precio) {
       this.id = id;
       this.ticket = ticket;
       this.prenda = prenda;
       this.precio = precio;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public Prenda getPrenda() {
        return this.prenda;
    }
    
    public void setPrenda(Prenda prenda) {
        this.prenda = prenda;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    public void insertar() {
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        
        session.save(this);
        session.getTransaction().commit();
        
        System.out.println("He insertado bien la venta ");
    }




}


